name: build-android-tools

on:
  workflow_dispatch:

jobs:
  linux-ubuntu:
    runs-on: ubuntu-26.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -q \
            cmake \
            ninja-build \
            clang \
            git \
            pandoc \
            libbrotli-dev \
            libgtest-dev \
            liblz4-dev \
            libpcre2-dev \
            libprotobuf-dev \
            libunwind-dev \
            libzstd-dev \
            pandoc \
            protobuf-compiler \
            pkg-config \
            xz-utils

      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 1
          show-progress: false

      - name: Configure git
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub Actions"

      - name: Generate adb man page
        run: |
          cd vendor/adb/docs/user
          pandoc -s -t man adb.1.md -o adb.1

      - name: Configure
        run: |
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX="$PWD/stage/usr/local" \
            -DANDROID_TOOLS_USE_BUNDLED_FMT=ON \
            -DANDROID_TOOLS_USE_BUNDLED_LIBUSB=ON

      - name: Build
        run: |
          cmake --build build --verbose

      - name: Install
        run: |
          cmake --install build \
            --strip

      - name: Prepare artifact
        run: |
          tar -cf android-tools-linux.tar -C stage .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: android-tools-linux
          path: android-tools-linux.tar
          archive: false
