name: build-android-tools

on:
  workflow_dispatch:

jobs:
  linux-ubuntu:
    runs-on: ubuntu-26.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q \
            cargo \
            clang-17 \
            cmake \
            git \
            libbrotli-dev \
            libgtest-dev \
            liblz4-dev \
            libpcre2-dev \
            libprotobuf-dev \
            libunwind-dev \
            libzstd-dev \
            make \
            ninja-build \
            pandoc \
            pkg-config \
            protobuf-compiler \
            xz-utils

      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: true
          fetch-depth: 1
          show-progress: false

      - name: Configure git
        run: |
          git config --global user.email "ci@example.com"
          git config --global user.name "GitHub Actions"

      - name: Generate adb man page
        run: |
          cd "vendor/adb/docs/user"
          pandoc -s -t man adb.1.md -o adb.1

      - name: Configure
        run: |
          cmake \
            -S . \
            -B build \
            -G Ninja \
            -DCMAKE_C_FLAGS="$CFLAGS" \
            -DCMAKE_CXX_FLAGS="$CXXFLAGS" \
            -DCMAKE_INSTALL_PREFIX="$PWD/android-tools/usr/local" \
            -DCMAKE_BUILD_TYPE=Release \
            -DANDROID_TOOLS_USE_BUNDLED_CORROSION=ON \
            -DANDROID_TOOLS_USE_BUNDLED_FMT=ON \
            -DANDROID_TOOLS_USE_BUNDLED_LIBUSB=ON \
            -DANDROID_TOOLS_ADB_ENABLE_MDNS=ON

      - name: Build
        run: |
          cmake --build build --verbose

      - name: Install
        run: |
          cmake --install build --strip

      - name: Prepare artifact
        run: |
          tar -cf android-tools-linux.tar -C android-tools .

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: android-tools-linux
          path: android-tools-linux.tar
          archive: false
